### ISSUE TITLE
cannot load such file -- esx_conn

### ISSUE THREAD

**Issue by alexpop** [chris-rock/inspec-vsphere#10]
This stops Chef Compliance builds as well:

```
[root@ap-cc6 libraries]# /opt/chef-compliance/embedded/bin/inspec exec https://github.com/chris-rock/inspec-vsphere/archive/master.tar.gz
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      ffi (>= 1.0.1)
      multi_json (~> 1.10)
      rspec (~> 3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- esx_conn (LoadError)
	from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from libraries/vsphere.rb:1:in `<main>'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/dsl_shared.rb:21:in `eval'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/dsl_shared.rb:21:in `require'
	from libraries/virtual_portgroup.rb:1:in `load_with_context'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:135:in `load_library_file'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:124:in `block in load_libraries'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:122:in `each'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:122:in `load_libraries'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/profile.rb:141:in `load_libraries'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/runner.rb:83:in `block in load'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/runner.rb:79:in `each'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/runner.rb:79:in `load'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/runner.rb:95:in `run'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/base_cli.rb:84:in `run_tests'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/lib/inspec/cli.rb:164:in `exec'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-1.4.1/bin/inspec:12:in `<top (required)>'
	from /opt/chef-compliance/embedded/bin/inspec:22:in `load'
	from /opt/chef-compliance/embedded/bin/inspec:22:in `<main>'
```

**Comment by chris-rock** [comment]
Thank you @alexpop for raising the issue. Not relevant for the latest implementation anymore, vmware support is also in train now
